USE ineedit_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS buyer;
DROP TABLE IF EXISTS seller;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS product_image_url;
DROP TABLE IF EXISTS seller_docs_url;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS cart_item;

SET FOREIGN_KEY_CHECKS = 1;

SOURCE schema.sql;
SOURCE mock_data.sql;

DELIMITER //
CREATE TRIGGER update_product_date_created
BEFORE INSERT ON product
FOR EACH ROW
BEGIN
    SET NEW.date_created = CURDATE();
END;
//